// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fo_msgs.proto

package com.pixelatedgames.fos.protobufs;

public final class FoMsgs {
  private FoMsgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum msg_type
      implements com.google.protobuf.Internal.EnumLite {
    PING(0, 1),
    LOGIN(1, 2),
    ;
    
    public static final int PING_VALUE = 1;
    public static final int LOGIN_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static msg_type valueOf(int value) {
      switch (value) {
        case 1: return PING;
        case 2: return LOGIN;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<msg_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<msg_type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<msg_type>() {
            public msg_type findValueByNumber(int number) {
              return msg_type.valueOf(number);
            }
          };
    
    private final int value;
    
    private msg_type(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.pixelatedgames.fos.protobufs.msg_type)
  }
  
  public interface fo_msgOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.pixelatedgames.fos.protobufs.msg_type type = 1;
    boolean hasType();
    com.pixelatedgames.fos.protobufs.FoMsgs.msg_type getType();
    
    // optional .com.pixelatedgames.fos.protobufs.ping _ping = 2;
    boolean hasPing();
    com.pixelatedgames.fos.protobufs.FoMsgs.ping getPing();
    
    // optional .com.pixelatedgames.fos.protobufs.gen _gen = 3;
    boolean hasGen();
    com.pixelatedgames.fos.protobufs.FoMsgs.gen getGen();
  }
  public static final class fo_msg extends
      com.google.protobuf.GeneratedMessageLite
      implements fo_msgOrBuilder {
    // Use fo_msg.newBuilder() to construct.
    private fo_msg(Builder builder) {
      super(builder);
    }
    private fo_msg(boolean noInit) {}
    
    private static final fo_msg defaultInstance;
    public static fo_msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public fo_msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .com.pixelatedgames.fos.protobufs.msg_type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.pixelatedgames.fos.protobufs.FoMsgs.msg_type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.pixelatedgames.fos.protobufs.FoMsgs.msg_type getType() {
      return type_;
    }
    
    // optional .com.pixelatedgames.fos.protobufs.ping _ping = 2;
    public static final int _PING_FIELD_NUMBER = 2;
    private com.pixelatedgames.fos.protobufs.FoMsgs.ping Ping_;
    public boolean hasPing() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.pixelatedgames.fos.protobufs.FoMsgs.ping getPing() {
      return Ping_;
    }
    
    // optional .com.pixelatedgames.fos.protobufs.gen _gen = 3;
    public static final int _GEN_FIELD_NUMBER = 3;
    private com.pixelatedgames.fos.protobufs.FoMsgs.gen Gen_;
    public boolean hasGen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.pixelatedgames.fos.protobufs.FoMsgs.gen getGen() {
      return Gen_;
    }
    
    private void initFields() {
      type_ = com.pixelatedgames.fos.protobufs.FoMsgs.msg_type.PING;
      Ping_ = com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance();
      Gen_ = com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPing()) {
        if (!getPing().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, Ping_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, Gen_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, Ping_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, Gen_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg, Builder>
        implements com.pixelatedgames.fos.protobufs.FoMsgs.fo_msgOrBuilder {
      // Construct using com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.pixelatedgames.fos.protobufs.FoMsgs.msg_type.PING;
        bitField0_ = (bitField0_ & ~0x00000001);
        Ping_ = com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        Gen_ = com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg getDefaultInstanceForType() {
        return com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg.getDefaultInstance();
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg build() {
        com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg buildPartial() {
        com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg result = new com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.Ping_ = Ping_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.Gen_ = Gen_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg other) {
        if (other == com.pixelatedgames.fos.protobufs.FoMsgs.fo_msg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        if (other.hasGen()) {
          mergeGen(other.getGen());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasPing()) {
          if (!getPing().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pixelatedgames.fos.protobufs.FoMsgs.msg_type value = com.pixelatedgames.fos.protobufs.FoMsgs.msg_type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.pixelatedgames.fos.protobufs.FoMsgs.ping.Builder subBuilder = com.pixelatedgames.fos.protobufs.FoMsgs.ping.newBuilder();
              if (hasPing()) {
                subBuilder.mergeFrom(getPing());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPing(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.pixelatedgames.fos.protobufs.FoMsgs.gen.Builder subBuilder = com.pixelatedgames.fos.protobufs.FoMsgs.gen.newBuilder();
              if (hasGen()) {
                subBuilder.mergeFrom(getGen());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGen(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.pixelatedgames.fos.protobufs.msg_type type = 1;
      private com.pixelatedgames.fos.protobufs.FoMsgs.msg_type type_ = com.pixelatedgames.fos.protobufs.FoMsgs.msg_type.PING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.pixelatedgames.fos.protobufs.FoMsgs.msg_type getType() {
        return type_;
      }
      public Builder setType(com.pixelatedgames.fos.protobufs.FoMsgs.msg_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.pixelatedgames.fos.protobufs.FoMsgs.msg_type.PING;
        
        return this;
      }
      
      // optional .com.pixelatedgames.fos.protobufs.ping _ping = 2;
      private com.pixelatedgames.fos.protobufs.FoMsgs.ping Ping_ = com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance();
      public boolean hasPing() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.pixelatedgames.fos.protobufs.FoMsgs.ping getPing() {
        return Ping_;
      }
      public Builder setPing(com.pixelatedgames.fos.protobufs.FoMsgs.ping value) {
        if (value == null) {
          throw new NullPointerException();
        }
        Ping_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPing(
          com.pixelatedgames.fos.protobufs.FoMsgs.ping.Builder builderForValue) {
        Ping_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePing(com.pixelatedgames.fos.protobufs.FoMsgs.ping value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            Ping_ != com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance()) {
          Ping_ =
            com.pixelatedgames.fos.protobufs.FoMsgs.ping.newBuilder(Ping_).mergeFrom(value).buildPartial();
        } else {
          Ping_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPing() {
        Ping_ = com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // optional .com.pixelatedgames.fos.protobufs.gen _gen = 3;
      private com.pixelatedgames.fos.protobufs.FoMsgs.gen Gen_ = com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance();
      public boolean hasGen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.pixelatedgames.fos.protobufs.FoMsgs.gen getGen() {
        return Gen_;
      }
      public Builder setGen(com.pixelatedgames.fos.protobufs.FoMsgs.gen value) {
        if (value == null) {
          throw new NullPointerException();
        }
        Gen_ = value;
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setGen(
          com.pixelatedgames.fos.protobufs.FoMsgs.gen.Builder builderForValue) {
        Gen_ = builderForValue.build();
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeGen(com.pixelatedgames.fos.protobufs.FoMsgs.gen value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            Gen_ != com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance()) {
          Gen_ =
            com.pixelatedgames.fos.protobufs.FoMsgs.gen.newBuilder(Gen_).mergeFrom(value).buildPartial();
        } else {
          Gen_ = value;
        }
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearGen() {
        Gen_ = com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pixelatedgames.fos.protobufs.fo_msg)
    }
    
    static {
      defaultInstance = new fo_msg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.fo_msg)
  }
  
  public interface pingOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required uint64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
  }
  public static final class ping extends
      com.google.protobuf.GeneratedMessageLite
      implements pingOrBuilder {
    // Use ping.newBuilder() to construct.
    private ping(Builder builder) {
      super(builder);
    }
    private ping(boolean noInit) {}
    
    private static final ping defaultInstance;
    public static ping getDefaultInstance() {
      return defaultInstance;
    }
    
    public ping getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required uint64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, timestamp_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pixelatedgames.fos.protobufs.FoMsgs.ping prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.pixelatedgames.fos.protobufs.FoMsgs.ping, Builder>
        implements com.pixelatedgames.fos.protobufs.FoMsgs.pingOrBuilder {
      // Construct using com.pixelatedgames.fos.protobufs.FoMsgs.ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.ping getDefaultInstanceForType() {
        return com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance();
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.ping build() {
        com.pixelatedgames.fos.protobufs.FoMsgs.ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pixelatedgames.fos.protobufs.FoMsgs.ping buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pixelatedgames.fos.protobufs.FoMsgs.ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.ping buildPartial() {
        com.pixelatedgames.fos.protobufs.FoMsgs.ping result = new com.pixelatedgames.fos.protobufs.FoMsgs.ping(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.pixelatedgames.fos.protobufs.FoMsgs.ping other) {
        if (other == com.pixelatedgames.fos.protobufs.FoMsgs.ping.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pixelatedgames.fos.protobufs.ping)
    }
    
    static {
      defaultInstance = new ping(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.ping)
  }
  
  public interface genOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated int32 nums = 1 [packed = true];
    java.util.List<java.lang.Integer> getNumsList();
    int getNumsCount();
    int getNums(int index);
    
    // repeated string strs = 2;
    java.util.List<String> getStrsList();
    int getStrsCount();
    String getStrs(int index);
  }
  public static final class gen extends
      com.google.protobuf.GeneratedMessageLite
      implements genOrBuilder {
    // Use gen.newBuilder() to construct.
    private gen(Builder builder) {
      super(builder);
    }
    private gen(boolean noInit) {}
    
    private static final gen defaultInstance;
    public static gen getDefaultInstance() {
      return defaultInstance;
    }
    
    public gen getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated int32 nums = 1 [packed = true];
    public static final int NUMS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> nums_;
    public java.util.List<java.lang.Integer>
        getNumsList() {
      return nums_;
    }
    public int getNumsCount() {
      return nums_.size();
    }
    public int getNums(int index) {
      return nums_.get(index);
    }
    private int numsMemoizedSerializedSize = -1;
    
    // repeated string strs = 2;
    public static final int STRS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList strs_;
    public java.util.List<String>
        getStrsList() {
      return strs_;
    }
    public int getStrsCount() {
      return strs_.size();
    }
    public String getStrs(int index) {
      return strs_.get(index);
    }
    
    private void initFields() {
      nums_ = java.util.Collections.emptyList();;
      strs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNumsList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(numsMemoizedSerializedSize);
      }
      for (int i = 0; i < nums_.size(); i++) {
        output.writeInt32NoTag(nums_.get(i));
      }
      for (int i = 0; i < strs_.size(); i++) {
        output.writeBytes(2, strs_.getByteString(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < nums_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(nums_.get(i));
        }
        size += dataSize;
        if (!getNumsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        numsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strs_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStrsList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FoMsgs.gen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pixelatedgames.fos.protobufs.FoMsgs.gen prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.pixelatedgames.fos.protobufs.FoMsgs.gen, Builder>
        implements com.pixelatedgames.fos.protobufs.FoMsgs.genOrBuilder {
      // Construct using com.pixelatedgames.fos.protobufs.FoMsgs.gen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nums_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        strs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.gen getDefaultInstanceForType() {
        return com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance();
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.gen build() {
        com.pixelatedgames.fos.protobufs.FoMsgs.gen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pixelatedgames.fos.protobufs.FoMsgs.gen buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pixelatedgames.fos.protobufs.FoMsgs.gen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pixelatedgames.fos.protobufs.FoMsgs.gen buildPartial() {
        com.pixelatedgames.fos.protobufs.FoMsgs.gen result = new com.pixelatedgames.fos.protobufs.FoMsgs.gen(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          nums_ = java.util.Collections.unmodifiableList(nums_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nums_ = nums_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          strs_ = new com.google.protobuf.UnmodifiableLazyStringList(
              strs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.strs_ = strs_;
        return result;
      }
      
      public Builder mergeFrom(com.pixelatedgames.fos.protobufs.FoMsgs.gen other) {
        if (other == com.pixelatedgames.fos.protobufs.FoMsgs.gen.getDefaultInstance()) return this;
        if (!other.nums_.isEmpty()) {
          if (nums_.isEmpty()) {
            nums_ = other.nums_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNumsIsMutable();
            nums_.addAll(other.nums_);
          }
          
        }
        if (!other.strs_.isEmpty()) {
          if (strs_.isEmpty()) {
            strs_ = other.strs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStrsIsMutable();
            strs_.addAll(other.strs_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              ensureNumsIsMutable();
              nums_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addNums(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              ensureStrsIsMutable();
              strs_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 nums = 1 [packed = true];
      private java.util.List<java.lang.Integer> nums_ = java.util.Collections.emptyList();;
      private void ensureNumsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nums_ = new java.util.ArrayList<java.lang.Integer>(nums_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getNumsList() {
        return java.util.Collections.unmodifiableList(nums_);
      }
      public int getNumsCount() {
        return nums_.size();
      }
      public int getNums(int index) {
        return nums_.get(index);
      }
      public Builder setNums(
          int index, int value) {
        ensureNumsIsMutable();
        nums_.set(index, value);
        
        return this;
      }
      public Builder addNums(int value) {
        ensureNumsIsMutable();
        nums_.add(value);
        
        return this;
      }
      public Builder addAllNums(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNumsIsMutable();
        super.addAll(values, nums_);
        
        return this;
      }
      public Builder clearNums() {
        nums_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      
      // repeated string strs = 2;
      private com.google.protobuf.LazyStringList strs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          strs_ = new com.google.protobuf.LazyStringArrayList(strs_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getStrsList() {
        return java.util.Collections.unmodifiableList(strs_);
      }
      public int getStrsCount() {
        return strs_.size();
      }
      public String getStrs(int index) {
        return strs_.get(index);
      }
      public Builder setStrs(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrsIsMutable();
        strs_.set(index, value);
        
        return this;
      }
      public Builder addStrs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrsIsMutable();
        strs_.add(value);
        
        return this;
      }
      public Builder addAllStrs(
          java.lang.Iterable<String> values) {
        ensureStrsIsMutable();
        super.addAll(values, strs_);
        
        return this;
      }
      public Builder clearStrs() {
        strs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      void addStrs(com.google.protobuf.ByteString value) {
        ensureStrsIsMutable();
        strs_.add(value);
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.pixelatedgames.fos.protobufs.gen)
    }
    
    static {
      defaultInstance = new gen(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.gen)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
