// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fo_msgs.proto

#ifndef PROTOBUF_fo_5fmsgs_2eproto__INCLUDED
#define PROTOBUF_fo_5fmsgs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace pixelatedgames {
namespace fos {
namespace protobufs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_fo_5fmsgs_2eproto();
void protobuf_AssignDesc_fo_5fmsgs_2eproto();
void protobuf_ShutdownFile_fo_5fmsgs_2eproto();

class fo_msg;
class ping;
class gen;

enum msg_type {
  PING = 1,
  LOGIN = 2
};
bool msg_type_IsValid(int value);
const msg_type msg_type_MIN = PING;
const msg_type msg_type_MAX = LOGIN;
const int msg_type_ARRAYSIZE = msg_type_MAX + 1;

// ===================================================================

class fo_msg : public ::google::protobuf::MessageLite {
 public:
  fo_msg();
  virtual ~fo_msg();
  
  fo_msg(const fo_msg& from);
  
  inline fo_msg& operator=(const fo_msg& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const fo_msg& default_instance();
  
  void Swap(fo_msg* other);
  
  // implements Message ----------------------------------------------
  
  fo_msg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const fo_msg& from);
  void MergeFrom(const fo_msg& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .com.pixelatedgames.fos.protobufs.msg_type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline com::pixelatedgames::fos::protobufs::msg_type type() const;
  inline void set_type(com::pixelatedgames::fos::protobufs::msg_type value);
  
  // optional .com.pixelatedgames.fos.protobufs.ping _ping = 2;
  inline bool has__ping() const;
  inline void clear__ping();
  static const int kPingFieldNumber = 2;
  inline const ::com::pixelatedgames::fos::protobufs::ping& _ping() const;
  inline ::com::pixelatedgames::fos::protobufs::ping* mutable__ping();
  inline ::com::pixelatedgames::fos::protobufs::ping* release__ping();
  
  // optional .com.pixelatedgames.fos.protobufs.gen _gen = 3;
  inline bool has__gen() const;
  inline void clear__gen();
  static const int kGenFieldNumber = 3;
  inline const ::com::pixelatedgames::fos::protobufs::gen& _gen() const;
  inline ::com::pixelatedgames::fos::protobufs::gen* mutable__gen();
  inline ::com::pixelatedgames::fos::protobufs::gen* release__gen();
  
  // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.fo_msg)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has__ping();
  inline void clear_has__ping();
  inline void set_has__gen();
  inline void clear_has__gen();
  
  ::com::pixelatedgames::fos::protobufs::ping* _ping_;
  ::com::pixelatedgames::fos::protobufs::gen* _gen_;
  int type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_fo_5fmsgs_2eproto();
  friend void protobuf_AssignDesc_fo_5fmsgs_2eproto();
  friend void protobuf_ShutdownFile_fo_5fmsgs_2eproto();
  
  void InitAsDefaultInstance();
  static fo_msg* default_instance_;
};
// -------------------------------------------------------------------

class ping : public ::google::protobuf::MessageLite {
 public:
  ping();
  virtual ~ping();
  
  ping(const ping& from);
  
  inline ping& operator=(const ping& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const ping& default_instance();
  
  void Swap(ping* other);
  
  // implements Message ----------------------------------------------
  
  ping* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ping& from);
  void MergeFrom(const ping& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline ::google::protobuf::uint64 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.ping)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  
  ::google::protobuf::uint64 timestamp_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_fo_5fmsgs_2eproto();
  friend void protobuf_AssignDesc_fo_5fmsgs_2eproto();
  friend void protobuf_ShutdownFile_fo_5fmsgs_2eproto();
  
  void InitAsDefaultInstance();
  static ping* default_instance_;
};
// -------------------------------------------------------------------

class gen : public ::google::protobuf::MessageLite {
 public:
  gen();
  virtual ~gen();
  
  gen(const gen& from);
  
  inline gen& operator=(const gen& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const gen& default_instance();
  
  void Swap(gen* other);
  
  // implements Message ----------------------------------------------
  
  gen* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const gen& from);
  void MergeFrom(const gen& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated int32 nums = 1 [packed = true];
  inline int nums_size() const;
  inline void clear_nums();
  static const int kNumsFieldNumber = 1;
  inline ::google::protobuf::int32 nums(int index) const;
  inline void set_nums(int index, ::google::protobuf::int32 value);
  inline void add_nums(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      nums() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_nums();
  
  // repeated string strs = 2;
  inline int strs_size() const;
  inline void clear_strs();
  static const int kStrsFieldNumber = 2;
  inline const ::std::string& strs(int index) const;
  inline ::std::string* mutable_strs(int index);
  inline void set_strs(int index, const ::std::string& value);
  inline void set_strs(int index, const char* value);
  inline void set_strs(int index, const char* value, size_t size);
  inline ::std::string* add_strs();
  inline void add_strs(const ::std::string& value);
  inline void add_strs(const char* value);
  inline void add_strs(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& strs() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strs();
  
  // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.gen)
 private:
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > nums_;
  mutable int _nums_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strs_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_fo_5fmsgs_2eproto();
  friend void protobuf_AssignDesc_fo_5fmsgs_2eproto();
  friend void protobuf_ShutdownFile_fo_5fmsgs_2eproto();
  
  void InitAsDefaultInstance();
  static gen* default_instance_;
};
// ===================================================================


// ===================================================================

// fo_msg

// required .com.pixelatedgames.fos.protobufs.msg_type type = 1;
inline bool fo_msg::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void fo_msg::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void fo_msg::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void fo_msg::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline com::pixelatedgames::fos::protobufs::msg_type fo_msg::type() const {
  return static_cast< com::pixelatedgames::fos::protobufs::msg_type >(type_);
}
inline void fo_msg::set_type(com::pixelatedgames::fos::protobufs::msg_type value) {
  GOOGLE_DCHECK(com::pixelatedgames::fos::protobufs::msg_type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .com.pixelatedgames.fos.protobufs.ping _ping = 2;
inline bool fo_msg::has__ping() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void fo_msg::set_has__ping() {
  _has_bits_[0] |= 0x00000002u;
}
inline void fo_msg::clear_has__ping() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void fo_msg::clear__ping() {
  if (_ping_ != NULL) _ping_->::com::pixelatedgames::fos::protobufs::ping::Clear();
  clear_has__ping();
}
inline const ::com::pixelatedgames::fos::protobufs::ping& fo_msg::_ping() const {
  return _ping_ != NULL ? *_ping_ : *default_instance_->_ping_;
}
inline ::com::pixelatedgames::fos::protobufs::ping* fo_msg::mutable__ping() {
  set_has__ping();
  if (_ping_ == NULL) _ping_ = new ::com::pixelatedgames::fos::protobufs::ping;
  return _ping_;
}
inline ::com::pixelatedgames::fos::protobufs::ping* fo_msg::release__ping() {
  clear_has__ping();
  ::com::pixelatedgames::fos::protobufs::ping* temp = _ping_;
  _ping_ = NULL;
  return temp;
}

// optional .com.pixelatedgames.fos.protobufs.gen _gen = 3;
inline bool fo_msg::has__gen() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void fo_msg::set_has__gen() {
  _has_bits_[0] |= 0x00000004u;
}
inline void fo_msg::clear_has__gen() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void fo_msg::clear__gen() {
  if (_gen_ != NULL) _gen_->::com::pixelatedgames::fos::protobufs::gen::Clear();
  clear_has__gen();
}
inline const ::com::pixelatedgames::fos::protobufs::gen& fo_msg::_gen() const {
  return _gen_ != NULL ? *_gen_ : *default_instance_->_gen_;
}
inline ::com::pixelatedgames::fos::protobufs::gen* fo_msg::mutable__gen() {
  set_has__gen();
  if (_gen_ == NULL) _gen_ = new ::com::pixelatedgames::fos::protobufs::gen;
  return _gen_;
}
inline ::com::pixelatedgames::fos::protobufs::gen* fo_msg::release__gen() {
  clear_has__gen();
  ::com::pixelatedgames::fos::protobufs::gen* temp = _gen_;
  _gen_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ping

// required uint64 timestamp = 1;
inline bool ping::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ping::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ping::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ping::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 ping::timestamp() const {
  return timestamp_;
}
inline void ping::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// -------------------------------------------------------------------

// gen

// repeated int32 nums = 1 [packed = true];
inline int gen::nums_size() const {
  return nums_.size();
}
inline void gen::clear_nums() {
  nums_.Clear();
}
inline ::google::protobuf::int32 gen::nums(int index) const {
  return nums_.Get(index);
}
inline void gen::set_nums(int index, ::google::protobuf::int32 value) {
  nums_.Set(index, value);
}
inline void gen::add_nums(::google::protobuf::int32 value) {
  nums_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
gen::nums() const {
  return nums_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
gen::mutable_nums() {
  return &nums_;
}

// repeated string strs = 2;
inline int gen::strs_size() const {
  return strs_.size();
}
inline void gen::clear_strs() {
  strs_.Clear();
}
inline const ::std::string& gen::strs(int index) const {
  return strs_.Get(index);
}
inline ::std::string* gen::mutable_strs(int index) {
  return strs_.Mutable(index);
}
inline void gen::set_strs(int index, const ::std::string& value) {
  strs_.Mutable(index)->assign(value);
}
inline void gen::set_strs(int index, const char* value) {
  strs_.Mutable(index)->assign(value);
}
inline void gen::set_strs(int index, const char* value, size_t size) {
  strs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* gen::add_strs() {
  return strs_.Add();
}
inline void gen::add_strs(const ::std::string& value) {
  strs_.Add()->assign(value);
}
inline void gen::add_strs(const char* value) {
  strs_.Add()->assign(value);
}
inline void gen::add_strs(const char* value, size_t size) {
  strs_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
gen::strs() const {
  return strs_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
gen::mutable_strs() {
  return &strs_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobufs
}  // namespace fos
}  // namespace pixelatedgames
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fo_5fmsgs_2eproto__INCLUDED
