// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fantasy_messages.proto

package com.pixelatedgames.fos.protobufs;

public final class FantasyMessages {
  private FantasyMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum fantasy_message_type
      implements com.google.protobuf.Internal.EnumLite {
    LOGIN(0, 1),
    POSITION(1, 2),
    ;
    
    public static final int LOGIN_VALUE = 1;
    public static final int POSITION_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static fantasy_message_type valueOf(int value) {
      switch (value) {
        case 1: return LOGIN;
        case 2: return POSITION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<fantasy_message_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<fantasy_message_type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<fantasy_message_type>() {
            public fantasy_message_type findValueByNumber(int number) {
              return fantasy_message_type.valueOf(number);
            }
          };
    
    private final int value;
    
    private fantasy_message_type(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.pixelatedgames.fos.protobufs.fantasy_message_type)
  }
  
  public interface fantasy_messageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.pixelatedgames.fos.protobufs.fantasy_message_type type = 1;
    boolean hasType();
    com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type getType();
    
    // optional .com.pixelatedgames.fos.protobufs.login _login = 2;
    boolean hasLogin();
    com.pixelatedgames.fos.protobufs.FantasyMessages.login getLogin();
  }
  public static final class fantasy_message extends
      com.google.protobuf.GeneratedMessageLite
      implements fantasy_messageOrBuilder {
    // Use fantasy_message.newBuilder() to construct.
    private fantasy_message(Builder builder) {
      super(builder);
    }
    private fantasy_message(boolean noInit) {}
    
    private static final fantasy_message defaultInstance;
    public static fantasy_message getDefaultInstance() {
      return defaultInstance;
    }
    
    public fantasy_message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .com.pixelatedgames.fos.protobufs.fantasy_message_type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type getType() {
      return type_;
    }
    
    // optional .com.pixelatedgames.fos.protobufs.login _login = 2;
    public static final int _LOGIN_FIELD_NUMBER = 2;
    private com.pixelatedgames.fos.protobufs.FantasyMessages.login Login_;
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.pixelatedgames.fos.protobufs.FantasyMessages.login getLogin() {
      return Login_;
    }
    
    private void initFields() {
      type_ = com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type.LOGIN;
      Login_ = com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLogin()) {
        if (!getLogin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, Login_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, Login_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message, Builder>
        implements com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_messageOrBuilder {
      // Construct using com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        Login_ = com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message getDefaultInstanceForType() {
        return com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message.getDefaultInstance();
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message build() {
        com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message buildPartial() {
        com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message result = new com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.Login_ = Login_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message other) {
        if (other == com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasLogin()) {
          if (!getLogin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type value = com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.pixelatedgames.fos.protobufs.FantasyMessages.login.Builder subBuilder = com.pixelatedgames.fos.protobufs.FantasyMessages.login.newBuilder();
              if (hasLogin()) {
                subBuilder.mergeFrom(getLogin());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLogin(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.pixelatedgames.fos.protobufs.fantasy_message_type type = 1;
      private com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type type_ = com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type.LOGIN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type getType() {
        return type_;
      }
      public Builder setType(com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.pixelatedgames.fos.protobufs.FantasyMessages.fantasy_message_type.LOGIN;
        
        return this;
      }
      
      // optional .com.pixelatedgames.fos.protobufs.login _login = 2;
      private com.pixelatedgames.fos.protobufs.FantasyMessages.login Login_ = com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance();
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.pixelatedgames.fos.protobufs.FantasyMessages.login getLogin() {
        return Login_;
      }
      public Builder setLogin(com.pixelatedgames.fos.protobufs.FantasyMessages.login value) {
        if (value == null) {
          throw new NullPointerException();
        }
        Login_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setLogin(
          com.pixelatedgames.fos.protobufs.FantasyMessages.login.Builder builderForValue) {
        Login_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeLogin(com.pixelatedgames.fos.protobufs.FantasyMessages.login value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            Login_ != com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance()) {
          Login_ =
            com.pixelatedgames.fos.protobufs.FantasyMessages.login.newBuilder(Login_).mergeFrom(value).buildPartial();
        } else {
          Login_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearLogin() {
        Login_ = com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pixelatedgames.fos.protobufs.fantasy_message)
    }
    
    static {
      defaultInstance = new fantasy_message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.fantasy_message)
  }
  
  public interface loginOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int64 authentication = 2;
    boolean hasAuthentication();
    long getAuthentication();
  }
  public static final class login extends
      com.google.protobuf.GeneratedMessageLite
      implements loginOrBuilder {
    // Use login.newBuilder() to construct.
    private login(Builder builder) {
      super(builder);
    }
    private login(boolean noInit) {}
    
    private static final login defaultInstance;
    public static login getDefaultInstance() {
      return defaultInstance;
    }
    
    public login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int64 authentication = 2;
    public static final int AUTHENTICATION_FIELD_NUMBER = 2;
    private long authentication_;
    public boolean hasAuthentication() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getAuthentication() {
      return authentication_;
    }
    
    private void initFields() {
      authentication_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAuthentication()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, authentication_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, authentication_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pixelatedgames.fos.protobufs.FantasyMessages.login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pixelatedgames.fos.protobufs.FantasyMessages.login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.pixelatedgames.fos.protobufs.FantasyMessages.login, Builder>
        implements com.pixelatedgames.fos.protobufs.FantasyMessages.loginOrBuilder {
      // Construct using com.pixelatedgames.fos.protobufs.FantasyMessages.login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        authentication_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.login getDefaultInstanceForType() {
        return com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance();
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.login build() {
        com.pixelatedgames.fos.protobufs.FantasyMessages.login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pixelatedgames.fos.protobufs.FantasyMessages.login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pixelatedgames.fos.protobufs.FantasyMessages.login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pixelatedgames.fos.protobufs.FantasyMessages.login buildPartial() {
        com.pixelatedgames.fos.protobufs.FantasyMessages.login result = new com.pixelatedgames.fos.protobufs.FantasyMessages.login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authentication_ = authentication_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.pixelatedgames.fos.protobufs.FantasyMessages.login other) {
        if (other == com.pixelatedgames.fos.protobufs.FantasyMessages.login.getDefaultInstance()) return this;
        if (other.hasAuthentication()) {
          setAuthentication(other.getAuthentication());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAuthentication()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              authentication_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 authentication = 2;
      private long authentication_ ;
      public boolean hasAuthentication() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getAuthentication() {
        return authentication_;
      }
      public Builder setAuthentication(long value) {
        bitField0_ |= 0x00000001;
        authentication_ = value;
        
        return this;
      }
      public Builder clearAuthentication() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authentication_ = 0L;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pixelatedgames.fos.protobufs.login)
    }
    
    static {
      defaultInstance = new login(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pixelatedgames.fos.protobufs.login)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
